name: my_weather
description: A flutter app for weather forecast
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # Redux
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  flutter_redux_navigation: ^0.6.0

  # Auth
  flutter_appauth: ^0.9.1

  # Network
  http: ^0.12.2

  # Cache
  shared_preferences: ^0.5.12+2

  # DI
  get_it: ^4.0.4

  # Location
  geolocator: ^6.1.3

  # Utilities
  url_launcher: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/my-weather.jpg
    - assets/icons/my-weather.png

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 700
